services:
  opensearch:
    image: opensearchproject/opensearch:2
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - opensearch-local-data:/usr/share/opensearch/data
    networks:
      - opensearch-local-net
  dashboard:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - "5601:5601"
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    networks:
      - opensearch-local-net
volumes:
  opensearch-local-data:

networks:
  opensearch-local-net:
