### This is the Terraform-generated dev-build.yml workflow for the timdex-index-manager-dev app repository ###
name: Dev Build and Deploy Fargate Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  deploy:
    name: Dev Deploy Fargate Container
    uses: mitlibraries/.github/.github/workflows/fargate-shared-deploy-dev.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "timdex-index-manager-gha-dev"
      ECR: "timdex-index-manager-dev"
